### PR TITLE
Introduce equivalence constraints in constraint generation

### LINKED ISSUE #36: impossible branches are not ignored
With #34, the following test fails:

~~~erlang
-module(test).

-compile(export_all).

-spec foo2 (a) -> 1; (b) -> 2.
foo2(X) ->
    case X of
        a -> 1;
        b -> 2
    end.
~~~

We now investigate what happens when `foo2` is type-checked against `(a) -> 1`. 
For the `case X of ...` part, the following constraints are generated:

~~~
{"case branch":10:1,
      #{A1@0 => $3, X@0 => $4},
      [],
      [{ccase,
        "case":11:5,
        [{cvar, "var X@0":11:10, X@0, $5},
         {csubty, "exhaustiveness check":11:5, $5, a | b}],
        [{"case branch":12:9,
          #{X@0 => $5 /\ a},
          [],
          [{csubty, "int literal":12:14, 1, $6}],
          $5 /\ a},
         {"case branch":13:9,
          #{X@0 => ($5 /\ not(a)) /\ b},
          [],
          [{csubty, "int literal":13:14, 2, $6}],
          ($5 /\ not(a)) /\ b}]},
       {csubty, "result of case":11:5, $6, $1}],
      $0 /\ ({any()} /\ {any()})}
~~~

Here `$5` is a fresh type variable generated for the scrutiny `X`. From the environment, we get that `$4` (the type of `X@0`) must be `a`.

The contraints above can be broken down as follows:

Constraints for the scrutiny X:

~~~
        [{cvar, "var X@0":11:10, X@0, $5},
         {csubty, "exhaustiveness check":11:5, $5, a | b}],
~~~

These two constraints require that the type of `X` is a subtype of `$5` and the exhaustiveness check requires `$5 <= a | b`. By knowing that `X@0` has type `a`, **this should give us the substitution** `<$5 -> a>`.

Constraints for the first clause:

~~~
        {"case branch":12:9,
          #{X@0 => $5 /\ a},
          [],
          [{csubty, "int literal":12:14, 1, $6}],
          $5 /\ a}
~~~

The env `#{X@0 => $5 /\ a}` refines the type of `X`, `$6` is a fresh type variable for the result type. `$5 /\ a` is the guard type of the clause: only if this type is not bottom, the clause can be taken. Under the substitution `<$5 -> a>`, the guard type becomes `a`, which is not bottom.

Constraints for the second clause:

~~~
         {"case branch":13:9,
          #{X@0 => ($5 /\ not(a)) /\ b},
          [],
          [{csubty, "int literal":13:14, 2, $6}],
          ($5 /\ not(a)) /\ b}]}
~~~

This is very similar to the first clause. The guard type is now `($5 /\ not(a)) /\ b`, which can be simplified to `($5 /\ b)`. Under the substitution `<$5 -> a>`, the guard type becomes `a /\ b`, which is bottom. This reflects the fact that the second clause is impossible if the argument type is `a`.

The problem arises during constraint simplification. Here are the relevant parts from the log:

~~~
[DEBUG 2023-09-18 09:41:43.246 constr_simp.erl:101] Checking which branches of case at test.erl:11:5 should be ignored.
Env: {A1@0 => atom() /\ (mu8 | not(mu8) /\ a) |
         integer() /\ mu8 |
         tuple() /\ (mu8 /\ tuple()) |
         fun() /\ (mu8 /\ fun()),
 X@0 => atom() /\ (mu7 | not(mu7) /\ a) |
        integer() /\ mu7 |
        tuple() /\ (mu7 /\ tuple()) |
        fun() /\ (mu7 /\ fun())}
Fixed tyvars: [mu7,mu8]
Constraints for scrutiny:
{[{csubty, "exhaustiveness check":11:5, $5, a | b},
  {csubty,
   "var X@0":11:10,
   atom() /\ (mu7 | not(mu7) /\ a) |
   integer() /\ mu7 |
   tuple() /\ (mu7 /\ tuple()) |
   fun() /\ (mu7 /\ fun()),
   $5}]}
[DEBUG 2023-09-18 09:41:43.246 constr_simp.erl:111] Unique substitution:
{$5 => atom() /\ (mu15 /\ (a | b) | not(mu15) /\ a),
 mu7 => atom() /\ (mu14 /\ (mu15 /\ (a | b) | not(mu15) /\ a))}
~~~

We see that `X@0` does not get the type `a` but a much more complicated type:

~~~
        atom() /\ (mu7 | not(mu7) /\ a) |
        integer() /\ mu7 |
        tuple() /\ (mu7 /\ tuple()) |
        fun() /\ (mu7 /\ fun())
~~~

We can slightly simplify this type

~~~
        atom() /\ mu7 | 
        not(mu7) /\ a) |
        integer() /\ mu7 |
        tuple() /\ mu7 |
        fun() /\ mu7
~~~

But still, it's not the same as `a` (what we would expect). Hence, we get the following substitution:

~~~
<$5 -> mu15 /\ (a | b) | not(mu15) /\ a>
~~~

But under this substitution, the type `$5 /\ b` is not bottom, so the second branch ist not ignored.

### PR DESCRIPTION
**Pull request by skogsbaer**
This PR fixes #36 and #56. The problem of both bugs was that in a `case` expression

~~~erlang
case exp of ...
~~~

the scrutiny was assigned some fresh type variable `Alpha` and the real type of `exp` was required to be a subtype of `Alpha`. But the requirement to be just a subtype of `Alpha` was not strong enough because `Alpha` was then used in various constraints for checking the branches of the `case`.

As an example, consider the following function from #36:

~~~erlang
-spec f (a) -> 1; (b) -> 2.
f(X) ->
    case X of
        a -> 1;
        b -> 2
    end.
~~~

Now imagine we check the definition of `f` against type `(b) -> 2`. Then X has type `b`. During constraint generation, the scrutiny `X` gets assigned type `Alpha` with the constraint `b <= Alpha`. But this constraint is not strong enough for detecting that branch `a -> 1` is impossible. Essentially, tally assigns `Alpha` the type `b \/ Mu`, where `Mu` is some fresh type variable. To exclude the branch `a -> 1`, we would then need `(b \/ Mu) /\ a <= none()`, but clearly this does not hold.

This PR introduces an equivalence constraint for the scrutiny of a `case` (instead of just a subtype constraint). So for the example above, scrutiny `X` gets assigned type `Alpha` with the constraint `b ~ Alpha` (`b ~ Alpha` is just shorthand for `b <= Alpha` and `Alpha <= b`). Then tally assigns `Alpha` the type `b`, so `b /\ a <= none()` holds, so the branch is excluded from type checking.

### CODE REVIEW

**Comment by skogsbaer** [comment]
@albsch do not merge yet. There are some examples which do not work yet. But I think they can be made working.

**Comment by albsch** [comment]
Just checked, `inter_03_fail` seems to fail currently.

**Comment by skogsbaer** [comment]
This PR provides only a partial fix for #36. It successfully type checks the original example

~~~erlang
-spec f1 (a) -> 1; (b) -> 2.
f1(X) ->
    case X of
        a -> 1;
        b -> 2
    end.
~~~

But the following example does not type check:


~~~erlang
-spec g(a) -> c; (b) -> d.
g(a) -> c;
g(b) -> d.

-spec f4(a) -> 1; (b) -> 2.
f4(X) ->
    case g(X) of
        c -> 1;
        d -> 2
    end.
~~~

The problem is that the equivalence requirement does not propagate through function types. I'm working on a better solution.

**Comment by albsch** [comment]
Superseded by #100 .

**Pull request closed without merging**
